#!/bin/bash

# simple script to activate tor-proxy

#todo: check if interface is free for tor, else error or autochoose free

#path=/lib/systemd/system

if [[ $1 == "-d" || $1 == "--disable" ]]; then
        echo "Disabling tor-proxy..."
		systemctl disable --now tor
		sed -i 's/^TOR_IFNAME=.*$/TOR_IFNAME=/g' /etc/default/torproxy
		sed -i 's/^nameserver.*$//g' /etc/resolv.conf
elif [[ $1 == "-e" || $1 == "--enable" ]]; then
	if [[ -z $2 ]]; then	#-z $3 ]]; then
		echo "Please specify the tor-interface (exit)!"	# or set --auto -a!
	else
		if [[ ! $(systemctl status tor | grep 'Active: active (running') ]]; then
			echo "Enabling tor-proxy..."
			sed -i 's/^TOR_IFNAME=.*$/TOR_IFNAME='$2'/g' /etc/default/torproxy
			echo "nameserver 9.9.9.9" >> /etc/resolv.conf
			systemctl enable --now tor			
		else
			echo "Unknown error with service, check manually."
		fi

elif [[ $1 == "-h" || $1 == "--help" ]]; then
	echo ''
	echo 'Miniscript for control of tor-proxy.'
    echo ''
    echo 'torcontrol [opt1] [opt2]'
	echo ''
    echo '[opt1]:'
	echo '-d -disable      disable tor-proxy'
	echo ''
	echo '-e -enable       enable tor-proxy'
	echo '                 [opt2] interface for tor-entry, e.g. wlan0'
    echo ''
	echo ''
	echo ''
else
	echo ''
	echo 'Use -h for help-'
	echo ''
fi

